org: hamzadevops01
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
